### ISSUE TITLE
Unable to set the mode as "tcp"

### ISSUE THREAD

**Issue by rkalivarapu** [eea/eea.docker.haproxy#10]
Hi, 
I do not see an environment variable to set the mode as "tcp" to follow the below link to work on haproxy with ssl. Can you please enable us if possible?

https://serverfault.com/questions/236496/haproxy-not-passing-ssl-traffic-in-tcp-mode-unknown-protocol

**Comment by avoinea** [comment]
@rkalivarapu Thank you! It's fixed now. See tag `1.8-1.0`
