### ISSUE TITLE
Customize Cookie name

### ISSUE THREAD

**Issue by adrian-tarau** [eea/eea.docker.haproxy#22]
Currently, there is no way to push the name of the cookie (like JSESSIONID). There should be an environment variable (COOKIES_NAME?) to be used to inject the cookie from outside.

cookie JSESSIONID prefix nocache
server server1 host1:8080 cookie s1
server server1 host2:8080 cookie s2

**Comment by valentinab25** [comment]
I have added it in 1.8-1.7
