### ISSUE TITLE
Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : No such file or directory

### ISSUE THREAD

**Issue by mike-jewell** [eea/eea.docker.haproxy#25]
Hi There

I have just pulled the latest tag from docker.  When I run it I am now getting the following in the logs:

Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : No such file or directory

  haproxy_cms_service:
    image: eeacms/haproxy:1.8-1.5
    ports:
    - "4001:5000"
    - "1947:1936"
    networks:
      - cms-net
    environment:
      BACKENDS: "service:5000"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

When I roll back to version 1.8-1.5 the error goes away.

Thanks

**Comment by valentinab25** [comment]
Fixed in the latest image, released in 1.8-1.6
