### ISSUE TITLE
Servers are not configured in haproxy if version 2 of compose file is used

### ISSUE THREAD

**Issue by shibli786** [eea/eea.docker.haproxy#5]
hi i am using the version 2 of compose file 
version: '2'
services:
 haproxy:
  image: eeacms/haproxy:latest
  links:
   - web
  ports:
   - "80:5000"
   - "1936:1936"
 web:
  build: .
  #container_name: laravel_container
  volumes:
   - .:/var/www/html/app
  links:
   - mysql
 mysql:
  image: mysql:latest
  container_name: mysql_laravel
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: abcd
    MYSQL_PASSWORD: abcd
    MYSQL_DATABASE: laravel_db

After running docker-compose up -d
haproxy.cfg is configured as

global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  pidfile /etc/haproxy/haproxy.pid
  daemon
  # Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private
  # Default ciphers to use on SSL-enabled listening sockets.
  # For more information, see ciphers(1SSL). This list is from:
  #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
  ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
  ssl-default-bind-options no-sslv3
defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client  50000
  timeout server  50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http
  listen stats
    bind *:1936
    stats enable
    stats uri /
    stats hide-version
    stats auth admin:admin
  frontend http-frontend
    bind *:5000 
    mode http
    default_backend http-backend
  backend http-backend
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    cookie SRV_ID prefix

listen default
  bind *:4242

but no sever ip and port is listed to forward incoming connection. however when i use legacy format of compose file this is working perfectly.
how to fix this issue?

thanks for your time

**Comment by avoinea** [comment]
Add `BACKENDS` and `DNS_ENABLED` environment variables and use `depends_on` instead of `links` like:

```
haproxy:
  ...
  depends_on: 
  - web
  environment:
    BACKENDS: "web"
    DNS_ENABLED: "true"
```

See updated [README.md](https://github.com/eea/eea.docker.haproxy#run-with-docker-compose)
