### ISSUE TITLE
syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'

### ISSUE THREAD

**Issue by 10cody** [eea/eea.docker.haproxy#8]
$ docker run --env BACKENDS="127.0.0.1:8000 localhost:8000" eeacms/haproxy

syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'
command service cannot be started: [Errno 13] Permission denied
Setting up watches.
Watches established.

**Comment by avoinea** [comment]
Fixed.
