### ISSUE TITLE
Customize forwardfor

### ISSUE THREAD

**Issue by romeroyonatan** [eea/eea.docker.haproxy#9]
In our architecture we have a haproxy for balancing between docker nodes

```
                                        / Backend server
                         HAProxy(docker)- Backend server
                        /               \ Backend server
REQUEST ----> HAPRoxy---                               
              (main)    \               / Backend server
                         HAProxy(docker)- Backend server
                                        \ Backend server
```

We need the first X-Forward-For header of the main HAProxy server. It could be done customizing the option: `option forwardfor except <main-haproxy-ip>/32`

Thanks in advance

**Comment by avoinea** [comment]
@romeroyonatan 

* Can you detail a little bit. Where should this `option` be added? 
* Can you provide a working `haproxy.cfg` example?

Thank you!

**Comment by romeroyonatan** [comment]
I can customize configuration overwriting /tmp/haproxy.cfg
It works for me.
Thanks
